services:
  database:
    image: mariadb:11
    container_name: mariadb_server
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-admin}
      MYSQL_DATABASE: devfit_db
      MYSQL_USER: ${DB_USER:-app_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-app_pass}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    container_name: devfit_app
    depends_on:
      database:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/devfit_db
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-app_user}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-app_pass}
      JWT_SECRET_KEY: ${JWT_SECRET:-mySecretKeyForDevFitThatIsVeryLongAndSecure}
    restart: unless-stopped

volumes:
  mariadb_data: